# Generated by Django 5.1.6 on 2025-04-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0018_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
