# Generated by Django 5.1.6 on 2025-04-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0020_order_paid_alter_order_status_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escan.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escan.product')),
            ],
            options={
                'db_table': 'cart',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
