# Generated by Django 5.1.6 on 2025-04-20 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0021_customer_total_spent_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='total_spent',
        ),
    ]
