# Generated by Django 5.1.6 on 2025-04-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0023_alter_cart_unique_together_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
